package ca.mcgill.ecse321.museum.model;

import javax.persistence.Entity;

/**
 * Model class for a Manager, the code was partially generated by Umple.
 * Manager extends the abstract class MuseumUser.
 *
 * @author Siger
 * @author Kevin
 */
@Entity
public class Manager extends MuseumUser {

  // ------------------------
  // CONSTRUCTOR
  // ------------------------

  public Manager() {
  }

}
