package ca.mcgill.ecse321.museum.model;

import javax.persistence.*;

/**
 * Model class for a ScheduleOfTimePeriod, the code was partially generated by Umple.
 * Join table for the many-to-many relationship between TimePeriod and Schedule.
 *
 * @author Siger
 * @author Kevin
 */
@Entity
public class ScheduleOfTimePeriod {

  // ------------------------
  // MEMBER VARIABLES
  // ------------------------

  // ScheduleOfTimePeriod Attributes
  private long scheduleOfTimePeriodId;

  // ScheduleOfTimePeriod Associations
  private Schedule schedule;
  private TimePeriod timePeriod;

  // ------------------------
  // CONSTRUCTOR
  // ------------------------

  public ScheduleOfTimePeriod() {
  }

  // ------------------------
  // INTERFACE
  // ------------------------

  @GeneratedValue
  @Id
  public long getScheduleOfTimePeriodId() {
    return scheduleOfTimePeriodId;
  }

  /* Code from template association_GetOne */
  @ManyToOne()
  @JoinColumn(name = "schedule_id", referencedColumnName = "scheduleId", nullable = false)
  public Schedule getSchedule() {
    return schedule;
  }

  /* Code from template association_GetOne */
  @ManyToOne()
  @JoinColumn(name = "time_period_id", referencedColumnName = "timePeriodId", nullable = false)
  public TimePeriod getTimePeriod() {
    return timePeriod;
  }

  public boolean setScheduleOfTimePeriodId(long aScheduleOfTimePeriodId) {
    boolean wasSet = false;
    scheduleOfTimePeriodId = aScheduleOfTimePeriodId;
    wasSet = true;
    return wasSet;
  }

  /* Code from template association_SetUnidirectionalOne */
  public boolean setSchedule(Schedule aNewSchedule) {
    boolean wasSet = false;
    if (aNewSchedule != null) {
      schedule = aNewSchedule;
      wasSet = true;
    }
    return wasSet;
  }

  /* Code from template association_SetUnidirectionalOne */
  public boolean setTimePeriod(TimePeriod aNewTimePeriod) {
    boolean wasSet = false;
    if (aNewTimePeriod != null) {
      timePeriod = aNewTimePeriod;
      wasSet = true;
    }
    return wasSet;
  }
}
