package ca.mcgill.ecse321.museum.model;

import javax.persistence.*;

/**
 * Model class for a Schedule, the code was partially generated by Umple.
 * 
 * @author Siger
 * @author Kevin
 */
@Entity
public class Schedule {

  // ------------------------
  // MEMBER VARIABLES
  // ------------------------

  // Schedule Attributes
  private long scheduleId;

  // ------------------------
  // CONSTRUCTOR
  // ------------------------

  public Schedule() {}

  // ------------------------
  // INTERFACE
  // ------------------------

  @GeneratedValue
  @Id
  public long getScheduleId() {
    return scheduleId;
  }

  public boolean setScheduleId(long aScheduleId) {
    boolean wasSet = false;
    scheduleId = aScheduleId;
    wasSet = true;
    return wasSet;
  }
}
