package ca.mcgill.ecse321.museum.model;

import java.sql.Date;
import javax.persistence.*;

/**
 * Model class for a Ticket, the code was partially generated by Umple.
 * 
 * @author Siger
 * @author Kevin
 */
@Entity
public class Ticket {

  // ------------------------
  // MEMBER VARIABLES
  // ------------------------

  // Ticket Attributes
  private long ticketId;
  private Date visitDate;

  // Ticket Associations
  private Visitor visitor;

  // ------------------------
  // CONSTRUCTOR
  // ------------------------

  public Ticket() {}

  // ------------------------
  // INTERFACE
  // ------------------------

  @GeneratedValue
  @Id
  public long getTicketId() {
    return ticketId;
  }

  @Column(nullable = false)
  public Date getVisitDate() {
    return visitDate;
  }

  /* Code from template association_GetOne */
  @ManyToOne()
  @JoinColumn(name="visitor_id", referencedColumnName = "museumUserId", nullable = false)
  public Visitor getVisitor() {
    return visitor;
  }

  public boolean setTicketId(long aTicketId) {
    boolean wasSet = false;
    ticketId = aTicketId;
    wasSet = true;
    return wasSet;
  }

  public boolean setVisitDate(Date aVisitDate) {
    boolean wasSet = false;
    visitDate = aVisitDate;
    wasSet = true;
    return wasSet;
  }

  /* Code from template association_SetUnidirectionalOne */
  public boolean setVisitor(Visitor aNewVisitor) {
    boolean wasSet = false;
    if (aNewVisitor != null) {
      visitor = aNewVisitor;
      wasSet = true;
    }
    return wasSet;
  }
}
