package ca.mcgill.ecse321.museum.model;

import java.sql.Date;
import javax.persistence.*;

/**
 * Model class for a TimePeriod, the code was partially generated by Umple.
 * 
 * @author Siger
 * @author Kevin
 */
@Entity
public class TimePeriod {

  // ------------------------
  // MEMBER VARIABLES
  // ------------------------

  // TimePeriod Attributes
  private long timePeriodId;
  private Date startDate;
  private Date endDate;

  // ------------------------
  // CONSTRUCTOR
  // ------------------------

  public TimePeriod() {}

  // ------------------------
  // INTERFACE
  // ------------------------

  @GeneratedValue
  @Id
  public long getTimePeriodId() {
    return timePeriodId;
  }

  @Column(nullable = false)
  public Date getStartDate() {
    return startDate;
  }

  @Column(nullable = false)
  public Date getEndDate() {
    return endDate;
  }

  public boolean setTimePeriodId(long aTimePeriodId) {
    boolean wasSet = false;
    timePeriodId = aTimePeriodId;
    wasSet = true;
    return wasSet;
  }

  public boolean setStartDate(Date aStartDate) {
    boolean wasSet = false;
    startDate = aStartDate;
    wasSet = true;
    return wasSet;
  }

  public boolean setEndDate(Date aEndDate) {
    boolean wasSet = false;
    endDate = aEndDate;
    wasSet = true;
    return wasSet;
  }
}
