package ca.mcgill.ecse321.museum.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import java.sql.Timestamp;

/**
 * Model class for a TimePeriod, the code was partially generated by Umple.
 *
 * @author Siger
 * @author Kevin
 */
@Entity
public class TimePeriod {

  // ------------------------
  // MEMBER VARIABLES
  // ------------------------

  // TimePeriod Attributes
  private long timePeriodId;
  private Timestamp startDate;
  private Timestamp endDate;

  // ------------------------
  // CONSTRUCTOR
  // ------------------------

  public TimePeriod() {
  }

  // ------------------------
  // INTERFACE
  // ------------------------

  @GeneratedValue
  @Id
  public long getTimePeriodId() {
    return timePeriodId;
  }

  @Column(nullable = false, columnDefinition = "TIMESTAMP")
  public Timestamp getStartDate() {
    return startDate;
  }

  @Column(nullable = false, columnDefinition = "TIMESTAMP")
  public Timestamp getEndDate() {
    return endDate;
  }

  public boolean setTimePeriodId(long aTimePeriodId) {
    boolean wasSet = false;
    timePeriodId = aTimePeriodId;
    wasSet = true;
    return wasSet;
  }

  public boolean setStartDate(Timestamp aStartDate) {
    boolean wasSet = false;
    startDate = aStartDate;
    wasSet = true;
    return wasSet;
  }

  public boolean setEndDate(Timestamp aEndDate) {
    boolean wasSet = false;
    endDate = aEndDate;
    wasSet = true;
    return wasSet;
  }
}
